//! fabq_rc_binary_reader — Read .fabqrc binary files in Rust
//!
//! Generated by `fabq_rc_export.py`. Reads the custom FABQ-RC binary format.

use std::fs::File;
use std::io::{Read, Result as IoResult};
use std::path::Path;
use std::collections::HashMap;

const MAGIC: [u8; 4] = [b'F', b'Q', b'R', b'C'];

#[derive(Debug)]
pub struct FabqrcHeader {
    pub version: u16,
    pub allocation_len: u32,
    pub blocksize: u32,
    pub out_features: u32,
    pub in_features: u32,
}

#[derive(Debug, Clone)]
pub enum ChannelData {
    Int8 {
        scale: f32,
        data: Vec<i8>,
    },
    Binary {
        scales: Vec<f32>,
        packed: Vec<u8>,
    },
}

#[derive(Debug)]
pub struct FabqrcLayer {
    pub header: FabqrcHeader,
    /// channel_id -> ChannelData, in order
    pub channels: Vec<(u8, ChannelData)>,
}

impl FabqrcLayer {
    /// Read a .fabqrc file
    pub fn from_file(path: &Path) -> IoResult<Self> {
        let mut file = File::open(path)?;
        let mut buffer = Vec::new();
        file.read_to_end(&mut buffer)?;
        Self::from_bytes(&buffer)
    }

    pub fn from_bytes(bytes: &[u8]) -> IoResult<Self> {
        let mut offset = 0;

        // ── Magic + version ────────────────────────────────────────────────
        let magic = &bytes[offset..offset+4];
        if magic != MAGIC {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("Invalid magic: {:?}", magic),
            ));
        }
        offset += 4;

        let version = read_u16(bytes, &mut offset);
        if version != 1 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("Unsupported version: {}", version),
            ));
        }

        let allocation_len = read_u32(bytes, &mut offset);
        let blocksize = read_u32(bytes, &mut offset);
        let out_features = read_u32(bytes, &mut offset);
        let in_features = read_u32(bytes, &mut offset);

        let header = FabqrcHeader {
            version,
            allocation_len,
            blocksize,
            out_features,
            in_features,
        };

        // ── Per-channel data ───────────────────────────────────────────────
        let mut channels = Vec::with_capacity(allocation_len as usize);

        for _ in 0..allocation_len {
            let channel_id = bytes[offset]; offset += 1;
            let type_flag = bytes[offset]; offset += 1;

            let ch_data = if type_flag == 0 {
                // Int8 channel
                let scale = read_f32(bytes, &mut offset);
                let data: Vec<i8> = bytes[offset..offset + blocksize as usize]
                    .iter().map(|&b| b as i8).collect();
                offset += blocksize as usize;
                ChannelData::Int8 { scale, data }
            } else {
                // Binary channel
                let n_blocks = read_u32(bytes, &mut offset);
                let scales: Vec<f32> = (0..n_blocks)
                    .map(|_| read_f32(bytes, &mut offset))
                    .collect();
                let n_bytes = blocksize as usize / 8;
                let packed: Vec<u8> = bytes[offset..offset + n_bytes].to_vec();
                offset += n_bytes;
                ChannelData::Binary { scales, packed }
            };

            channels.push((channel_id, ch_data));
        }

        Ok(Self { header, channels })
    }

    /// Dequantize the full weight matrix to f32
    /// Returns [out_features, in_features] row-major
    pub fn dequantize(&self) -> Vec<f32> {
        let blocksize = self.header.blocksize as usize;
        let out_features = self.header.out_features as usize;
        let in_features = self.header.in_features as usize;

        // Rebuild channel order: each "channel" corresponds to a row group
        // n_channels = allocation_len, each channel covers blocksize columns
        // Total: n_channels * blocksize = in_features
        let n_channels = self.header.allocation_len as usize;
        let mut weight = vec![0.0_f32; out_features * in_features];

        for (ch_id, ch_data) in &self.channels {
            let ch_idx = *ch_id as usize;
            if ch_idx >= n_channels {
                continue;
            }

            let col_start = ch_idx * blocksize;
            let col_end = (col_start + blocksize).min(in_features);

            match ch_data {
                ChannelData::Int8 { scale, data } => {
                    for j in 0..(col_end - col_start) {
                        let val = data[j] as f32 * scale;
                        // Scale to all out_features rows
                        for i in 0..out_features {
                            weight[i * in_features + col_start + j] = val;
                        }
                    }
                }
                ChannelData::Binary { scales, packed } => {
                    // Unpack 8 bits per byte
                    let n_blocks = blocksize / 8;
                    for block_idx in 0..n_blocks {
                        let scale = scales[block_idx];
                        for bit in 0..8 {
                            let pos = block_idx * 8 + bit;
                            if pos >= col_end - col_start {
                                break;
                            }
                            let byte_val = packed[block_idx];
                            let bit_val = (byte_val >> bit) & 1;
                            let val = (bit_val as f32) * scale;
                            for i in 0..out_features {
                                weight[i * in_features + col_start + pos] = val;
                            }
                        }
                    }
                }
            }
        }

        weight
    }
}

// ── Binary reading helpers ────────────────────────────────────────────────────

fn read_u16(bytes: &[u8], offset: &mut usize) -> u16 {
    let val = u16::from_le_bytes([bytes[*offset], bytes[*offset + 1]]);
    *offset += 2;
    val
}

fn read_u32(bytes: &[u8], offset: &mut usize) -> u32 {
    let val = u32::from_le_bytes([
        bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3],
    ]);
    *offset += 4;
    val
}

fn read_f32(bytes: &[u8], offset: &mut usize) -> f32 {
    let val = f32::from_le_bytes([
        bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3],
    ]);
    *offset += 4;
    val
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_magic_check() {
        assert_eq!(&MAGIC, b"FQRC");
    }
}
