name: quanot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - networkx
  - scikit-learn
  - pandas
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cpu
    - pyphi
    - cma
    - deap
    - black
    - ruff
    - pytest
